#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 运 动 场

# Name of the author
author: Wei

# Short bio or description (displayed in the header)
description: 轻重竞技之间

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/reverie.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: xiewei@protonmail.com
  facebook:
  flickr:
  github: athletik/athletik.github.io
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter: 
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: http://athletik.github.io
enforce_ssl: https://athletik.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: 

# Valine评论系统开关
valine:
  enable: true
  appid:  rqEagbQWOMjRIeKIzMTcB4DY-MdYXbMMI # your leancloud app id
  appkey: lfhqQNvVyRM4X5dln1vtaeMU # your leancloud app key
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki，v1.4.0+ 已废弃
  verify: true # Verification code，v1.4.0+ 已废弃
  placeholder: 请在此处留言 # comment box placeholder
  avatar:   # gravatar style
  guest_info: 昵称,邮件,网址 # custom comment header
  pageSize: 10 # pagination size
  # path: window.location.pathname #  v1.4.0+不要使用参数“app_key: 'LHvLGcwcauE5B2JpMxJ3lbtF',”
  recordIP: true # 是否记录评论者IP
  enableQQ: true # 是否启用昵称框自动获取QQ昵称和QQ头像, 默认关闭
  serverURLs: https://rqeagbqw.api.lncldglobal.com # 把xxxxxxxx替换成你自己AppID的前8位字符

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 12
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

